# Generated by Django 3.0.9 on 2022-03-04 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discussion',
        ),
        migrations.DeleteModel(
            name='forum',
        ),
    ]
